name: DeathMemory
main: com.deathmemory.DeathMemory
version: ${project.version}
author: YourName
description: 玩家死亡后生成头颅并收集掉落物，支持国际化与多功能开关。
commands:
  deathmemory:
    description: 管理员功能命令，支持 records 子命令
    usage: /deathmemory records
    permission: deathmemory.admin
    permission-message: 你没有权限使用此命令
  dm:
    description: 管理员功能命令（简写），支持 records 子命令
    usage: /dm records
    permission: deathmemory.admin
    permission-message: 你没有权限使用此命令
