name: Release DeathMemory
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Generate Changelog
        uses: mikepenz/release-changelog-builder-action@v4
        id: changelog
        with:
          configuration: .github/release-changelog-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/DeathMemory-*.jar
          body: |
            ## DeathMemory 插件发布
            - 版本: ${{ github.ref_name }}
            - 兼容: Spigot/Paper 1.16+，推荐 1.21.4
            - 依赖: JDK 17+
            - 功能：
              - 死亡后生成玩家头颅，掉落物一键提取
              - 头颅右键打开箱子界面
              - 管理员命令 /deathmemory records 或 /dm records
              - 国际化与功能开关
              - 持久化与自动构建
            
            **如有问题欢迎提交 issue！**
            
            ---
            
            ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
